"""Structural pattern matching on decoded headers (#93).

`match`/`case` dissection needs no code in `src/` to work — it falls
out of two facts pinned here as regression tests, since ARCHITECTURE.md
promises contributors both: `@dataclass` auto-generates
`__match_args__` from field declaration order, and every field with a
fixed wire vocabulary is an `IntEnum`, which subclasses `int`.
"""

from netprotocols import (
    ARP,
    IGMP,
    TCP,
    UDP,
    VLAN,
    ARPOperation,
    Ethernet,
    EtherType,
    ICMPv4,
    IPProtocol,
    IPv4,
    IPv6,
    decode_frame,
)
from test_corpus import CORPUS


class TestMatchArgsIsAutoGenerated:
    """The mechanism ARCHITECTURE.md attributes to `@dataclass`,
    pinned directly so a change to how headers are declared (a
    non-dataclass base, an explicit __match_args__ override) is
    caught rather than silently degrading positional matching."""

    def test_match_args_follows_field_declaration_order(self):
        assert Ethernet.__match_args__ == ("dst", "src", "ethertype")

    def test_a_wide_header_gets_match_args_too(self):
        assert IPv4.__match_args__[:3] == ("version", "ihl", "dscp")
        assert "options" in IPv4.__match_args__

    def test_positional_class_patterns_work(self, raw_eth_header):
        eth = Ethernet.decode(raw_eth_header)
        match eth:
            case Ethernet(dst, src, ethertype):
                assert dst == eth.dst
                assert src == eth.src
                assert ethertype == eth.ethertype
            case _:
                raise AssertionError("positional pattern did not match")


class TestIntEnumFieldsMatchByValue:
    """Every enum field is an IntEnum (an int subclass), so a value
    pattern binds the plain wire int the decoder stored — no cast, no
    adapter view to keep in sync with the raw field."""

    def test_ethertype_matches_a_named_value(self, raw_eth_header):
        eth = Ethernet.decode(raw_eth_header)
        match eth:
            case Ethernet(ethertype=EtherType.ARP):
                matched = True
            case _:
                matched = False
        assert matched
        assert eth.ethertype == EtherType.ARP == 0x0806

    def test_a_mismatched_value_pattern_does_not_match(self, raw_eth_header):
        eth = Ethernet.decode(raw_eth_header)
        match eth:
            case Ethernet(ethertype=EtherType.IPV4):
                matched = True
            case _:
                matched = False
        assert not matched

    def test_ip_protocol_matches_with_a_guard(self, raw_ipv4_header):
        ip = IPv4.decode(raw_ipv4_header)
        match ip:
            case IPv4(protocol=IPProtocol.TCP, ttl=t) if t > 32:
                result = f"long-lived TCP, ttl={t}"
            case IPv4(protocol=IPProtocol.TCP):
                result = "TCP"
            case _:
                result = "other"
        assert result == f"long-lived TCP, ttl={ip.ttl}"
        assert ip.ttl > 32

    def test_a_failing_guard_falls_through(self, raw_ipv4_header):
        ip = IPv4.decode(raw_ipv4_header)
        match ip:
            case IPv4(protocol=IPProtocol.TCP) if ip.ttl > 200:
                result = "improbable"
            case IPv4(protocol=IPProtocol.TCP):
                result = "ordinary"
            case _:
                result = "other"
        assert result == "ordinary"

    def test_a_keyword_pattern_needs_no_match_args(self):
        """The keyword form works on any attribute — the guarantee
        __match_args__ adds is the positional form, tested above."""
        arp_reply = ARP(
            htype=1,
            ptype=0x0800,
            hlen=6,
            plen=4,
            oper=ARPOperation.REPLY,
            sha="00:11:22:33:44:55",
            spa="10.0.0.1",
            tha="00:00:00:00:00:00",
            tpa="10.0.0.2",
        )
        match arp_reply:
            case ARP(oper=ARPOperation.REPLY):
                matched = True
            case _:
                matched = False
        assert matched


class TestSequencePatternsOverADecodedChain:
    """decode_frame's Packet.layers is a plain tuple, so the chain
    itself is matchable — combining class patterns with a wildcard
    tail, the shape shown in the README."""

    def test_matches_ethernet_ipv4_tcp(self):
        for _, _, frame in CORPUS:
            packet = decode_frame(frame, lax=True)
            match packet.layers:
                case (Ethernet(), IPv4(protocol=IPProtocol.TCP), TCP(), *_):
                    return
        raise AssertionError("no Ethernet/IPv4/TCP frame in the corpus")

    def test_matches_ethernet_ipv6_icmpv6(self):
        for _, _, frame in CORPUS:
            packet = decode_frame(frame, lax=True)
            match packet.layers:
                case (
                    Ethernet(),
                    IPv6(next_header=IPProtocol.IPV6_ICMP),
                    _,
                    *_,
                ):
                    return
        raise AssertionError("no Ethernet/IPv6/ICMPv6 frame in the corpus")

    def test_a_syn_only_segment_matches_its_guard(self):
        tcp = TCP(
            src_port=1234,
            dst_port=80,
            seq=1,
            ack=0,
            data_offset=5,
            reserved=0,
            flags=0b000000010,  # SYN
            window=0,
            checksum=0,
            urgent_pointer=0,
        )
        match tcp:
            case TCP(flags_str=f) if "SYN" in f and "ACK" not in f:
                kind = "SYN"
            case TCP(flags_str=f) if "SYN" in f and "ACK" in f:
                kind = "SYN-ACK"
            case _:
                kind = "other"
        assert kind == "SYN"

    def test_the_readme_dissector_example_runs_unmodified(self):
        """Copied verbatim from the README's "Structural pattern
        matching" section, so a change there that breaks it is caught
        here too."""
        found = {"connection": False, "tcp": False}
        for _, _, frame in CORPUS:
            packet = decode_frame(frame, lax=True)
            match packet.layers:
                case [
                    _,
                    IPv4(protocol=IPProtocol.TCP) as ip,
                    TCP(flags_str=f),
                    *_,
                ] if "SYN" in f and "ACK" not in f:
                    found["connection"] = True
                    assert ip.src
                case [_, IPv4() as ip, TCP(), *_]:
                    found["tcp"] = True
                    assert ip.src
                case _:
                    pass
        assert found["tcp"], "the corpus has no plain TCP-over-IPv4 frame"


class TestDegradingAFieldBreaksMatching:
    """The failure mode ARCHITECTURE.md warns contributors about: a
    field carrying a closed wire vocabulary that is a bare int, not an
    IntEnum, silently stops matching by value rather than raising."""

    def test_a_bare_int_field_does_not_match_an_enum_value_pattern(self):
        # IGMP.type is a plain int (no enum type), unlike Ethernet's
        # IntEnum-backed ethertype -- demonstrating the two are not
        # equivalent for match/case even though both hold "0x11".
        igmp = IGMP(type=0x11, max_resp_code=0, checksum=0, body=b"")
        assert not isinstance(igmp.type, EtherType)
        match igmp:
            case IGMP(type=EtherType.IPV4):  # 0x0800, not 0x11: never equal
                matched = True
            case _:
                matched = False
        assert not matched


class TestValuePatternMatchesTheRawWireInt:
    """isinstance(EtherType.IPV4, int) is the second half of what makes
    this work: a value pattern is an equality check, and IntEnum
    members compare equal to the plain int the decoder stored."""

    def test_intenum_members_are_ints(self):
        assert isinstance(EtherType.IPV4, int)
        assert isinstance(IPProtocol.TCP, int)

    def test_a_decoded_field_holds_a_plain_int_not_an_enum_instance(
        self, raw_eth_header
    ):
        eth = Ethernet.decode(raw_eth_header)
        assert type(eth.ethertype) is int
        assert eth.ethertype == EtherType.ARP


class TestVlanAndUdpAlsoMatch:
    """Spot-check two more headers so the guarantee is not implicitly
    scoped to just Ethernet/IPv4/TCP."""

    def test_vlan_tag_matches_by_ethertype(self):
        tag = VLAN(pcp=0, dei=0, vid=100, ethertype=EtherType.IPV4)
        match tag:
            case VLAN(ethertype=EtherType.IPV4, vid=vid):
                assert vid == 100
            case _:
                raise AssertionError("VLAN did not match")

    def test_udp_matches_positionally(self, raw_udp_header):
        udp = UDP.decode(raw_udp_header)
        match udp:
            case UDP(src_port, dst_port):
                assert (src_port, dst_port) == (udp.src_port, udp.dst_port)
            case _:
                raise AssertionError("UDP did not match positionally")

    def test_icmpv4_matches_by_type(self, raw_icmpv4_echo_request):
        icmp = ICMPv4.decode(raw_icmpv4_echo_request)
        match icmp:
            case ICMPv4(type=8, code=0):  # echo request
                matched = True
            case _:
                matched = False
        assert matched
